In [11]:
#!/usr/bin/env python3

#1.kutuphaneler eklenir
from cgi import test
import imp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#veriler alindi
#2.veri onisleme
#2.1 veri yukleme
veriler = pd.read_csv("veriler.csv")
#test

x = veriler.iloc[:,1:4].values #bagimsiz degisken
y = veriler.iloc[:,4:].values #bagimli degisken


#verileri egitim ve test icin bol ve verilerin olceklenmesi
from sklearn.model_selection import train_test_split #belli bir yere kadar deneme belli bir yerden sonra test olacak
#x bağımsız, y bapımlı değişken

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.33, random_state=0)

#verileri olcekle
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(x_train) #egit ve uygula
X_test = sc.transform(x_test) #ogrenmeden uygulama

from sklearn.linear_model import LogisticRegression
logr = LogisticRegression(random_state=0)
logr.fit(X_train, y_train)

#tahmin
y_pred = logr.predict(X_test)#tahmin et test verisi ile
print(x_test)
print(y_pred)

print(y_test)#gercek bilgi




[[164  66  32]
 [165  55  27]
 [167  62  55]
 [162  59  41]
 [125  36  11]
 [166  56  42]
 [155  50  44]
 [159  40  29]]
['e' 'e' 'e' 'e' 'k' 'e' 'e' 'e']
[['k']
 ['k']
 ['k']
 ['k']
 ['e']
 ['k']
 ['k']
 ['k']]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
